name: 'Build'

on: [push, pull_request, release]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build package
        run: dotnet build -c Release
        
      - name: Upload DLL
        uses: actions/upload-artifact@v3
        with:
          name: dll
          path: bin/Release/net6.0/*
        
      - name: Upload nupkg
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          path: bin/Release/*.nupkg