name: 'Build'

on: [push, pull_request, release]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build package
        run: dotnet build -c Release
        
      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: dll
          path: bin/Release/net6.0/*
        
      - name: Upload nupkg
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: bin/Release/*.nupkg
  
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: 
      - build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download DLL
        uses: actions/download-artifact@v3
        with:
          name: dll
        
      - name: Download nupkg
        uses: actions/download-artifact@v3
        with:
          name: nupkg
          
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.nupkg
            *.dll
            *.pdb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Publish to nuget.org
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
            